import static org.testng.Assert.assertTrue;

import org.testng.annotations.Test;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */


public class LibraryTest {
    private static final boolean True = true;

	@Test 
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
     
        
        assertTrue(True);
        
        System.out.println("first change push");
    }
    
}
